### ISSUE TITLE
Invalid path to font files

### ISSUE THREAD

**Issue by bbooth** [johnotander/ember-cli-weather-icons#5]
app.import is looking in the wrong path for the fonts.  The fonts are located in /font not /fonts.  Also the destDir is wrong based on what the css is looking for.  PR coming coming...

**Comment by bbooth** [comment]
Figured out the error I was getting due to a version mismatch in weather-icons.  The bower.json was at v1.2.1, but the blueprint didn't specify a version.  So when I installed in my project it pulled v1.3.2.  Apparently the /fonts directory was renamed to /font.  https://github.com/erikflowers/weather-icons/commit/b954ee6c694d09b04b71a40c48880f868acee7eb

**Comment by johnotander** [comment]
You rock @bbooth !

**Comment by bbooth** [comment]
Glad I could help :)
